module.exports = {
    BCRYPT_WORK_FACTOR: 10,
    SESSION_DURATION: 1000 * 60 * 60,
    SESSION_EXTENSION_DURATION: 1000 * 60 * 10,
    SESSION_SECRET_KEY: process.env.SESSION_SECRET_KEY,
    SESSION_SECURE_COOKIES: false,
    SESSION_EPHEMERAL_COOKIES: true,
    DATABASE_KEY: process.env.DATABASE_KEY
};